on:
  push:
    branches: [ '*' ]

jobs:
  run-python-unit-tests:
    name: Run python unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run unit test Dockerfile
        uses: ./.github/actions/unit-test-action
      
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test_results
          path: ${{ github.workspace }}/test_results

      - name: Check test results
        run: |
          cat test_results/test_output.txt
          if [ -f test_results/tests_failed.txt ]; then
            echo "Some tests failed. Check the test output files for details."
          else
            echo "All tests passed successfully."
          fi

      - name: Update measure.xmls
        run: |
          cat test_results/measure_check_output.txt
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add **/measure.xml
          if git diff --cached --quiet; then
            echo "No changes to measure.xml files. Skipping commit."
          else
            git commit -m "Auto-update measure.xml files by GitHub Actions"
            git push origin HEAD
          fi